collections:
  trips:
    output: true
  notes:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "_trips"
    values:
      layout: trip
  - scope:
      path: "_notes"
    values:
      layout: note
  - scope:
      path: "_projects"
    values:
      layout: project
