collections:
  trips:
    output: true
  notes:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "_trips"
    values:
      layout: trip
      extra_css:
        - /style/gpx.css
        - https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css
  - scope:
      path: "_notes"
    values:
      layout: note
  - scope:
      path: "_projects"
    values:
      layout: project
